"""PostgreSQL connections and transactional schema initialization."""
import os
import threading
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row
from dotenv import load_dotenv
from pathlib import Path


SCHEMA = """
CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE NOT NULL,
    salt TEXT NOT NULL, password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS login_attempts (client TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS login_attempts_by_client ON login_attempts(client, created);
CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id), name TEXT NOT NULL,
    description TEXT NOT NULL, created DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS project_images (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, filename TEXT NOT NULL,
    created DOUBLE PRECISION NOT NULL DEFAULT EXTRACT(EPOCH FROM clock_timestamp()),
    PRIMARY KEY(project_id, filename)
);
CREATE TABLE IF NOT EXISTS preferences (user_id BIGINT PRIMARY KEY REFERENCES users(id), value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS director_drafts (
    user_id BIGINT PRIMARY KEY REFERENCES users(id), version INTEGER NOT NULL CHECK(version > 0), value JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS legacy_imports (path TEXT PRIMARY KEY, applied DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS creative_profiles (user_id BIGINT PRIMARY KEY REFERENCES users(id), value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS director_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
    phase TEXT NOT NULL, request JSONB NOT NULL, response JSONB NOT NULL, created DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS generation_jobs (
    id TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id), operation TEXT NOT NULL,
    parameters JSONB NOT NULL, creative JSONB, state TEXT NOT NULL, progress DOUBLE PRECISION NOT NULL,
    message TEXT NOT NULL, filename TEXT, created DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS images (
    filename TEXT PRIMARY KEY, user_id BIGINT REFERENCES users(id), png BYTEA NOT NULL,
    metadata JSONB NOT NULL, created DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS image_feedback (
    user_id BIGINT NOT NULL REFERENCES users(id), filename TEXT NOT NULL REFERENCES images(filename),
    rating INTEGER NOT NULL CHECK(rating IN (-1,0,1)), note TEXT NOT NULL, updated DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(user_id, filename)
);
CREATE INDEX IF NOT EXISTS jobs_by_user ON generation_jobs(user_id, created DESC);
CREATE INDEX IF NOT EXISTS images_by_user ON images(user_id, created DESC);
CREATE INDEX IF NOT EXISTS director_runs_by_user ON director_runs(user_id, created DESC);
INSERT INTO schema_migrations VALUES (3, EXTRACT(EPOCH FROM clock_timestamp())) ON CONFLICT DO NOTHING;
"""


class Record(dict):
    """Named rows with positional access for existing count/query consumers."""
    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


def record_row(cursor):
    make = dict_row(cursor)
    return lambda values: Record(make(values))


class Database:
    def __init__(self, dsn=None):
        self.dsn = dsn
        self._initialized = False
        self._lock = threading.Lock()

    def url(self):
        load_dotenv(Path(__file__).resolve().parents[1] / ".env", override=False)
        dsn = self.dsn or os.environ.get("AZURAI_DATABASE_URL", "").strip()
        if not isinstance(dsn, str) or not dsn.startswith(("postgresql://", "postgres://")):
            raise RuntimeError("Cần cấu hình AZURAI_DATABASE_URL bằng URL PostgreSQL. Không còn sử dụng SQLite.")
        return dsn

    @contextmanager
    def connect(self):
        with psycopg.connect(self.url(), row_factory=record_row, connect_timeout=10) as db:
            with self._lock:
                if not self._initialized:
                    db.execute("SELECT pg_advisory_xact_lock(41001, 0)")
                    db.execute(SCHEMA)
                    db.commit()
                    self._initialized = True
            yield db
